/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package son.linux;

import son.Main;

public class App {
    public static void main(String[] args) {
        var test = new Main();
        System.out.println(test.testVal);
    }
}
